# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: Changelog$(Rev:+rr)

variables:
  - name: 'RequestedFor'
    value: '$(Build.RequestedFor)'
  - name: 'RequestedForEmail'
    value: '$(Build.RequestedForEmail)'

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: NodeTool@0
  inputs:
    versionSpec: '14.15'
  displayName: 'Install Node.js'

- script: node ./index.js --user="$(RequestedForEmail)" --name="$(RequestedFor)"
  displayName: 'Generate Changelog'
